name: Build Distributables of PyDEILabs

on:
  push:
    tags:
      - 'v*'  # Trigger on tags following semantic versioning (e.g., v1.0, v2.0.1)
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile -i pydeilabs.icns -i pydeilabs.ico pydeilabs.py  # Create standalone executable
        # Adjust options if needed, e.g., add --name, --icon for custom output names or icons

      - name: Archive build artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: pydeilabs-${{ matrix.os }}
          path: |
            dist/pydeilabs${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: pydeilabs*

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: pydeilabs*
